Работающая БД (без тестов)
sergeyrid/calcoolator pull request #1
Opened 2023-09-12 20:16 UTC by FedMam

2023-09-13 07:10 UTC, IDKWNTCMF requested changes
Тесты тоже в этот пр добавь.

2023-09-13 07:10 UTC, IDKWNTCMF commented on app/src/main/kotlin/DBOperator.kt
> +    fun getCalculations(num: Int) = transaction {
Лучше чтобы мы могли получать подотрезок из записей в БД, а не только какое-то количество с конца

2023-09-13 07:10 UTC, IDKWNTCMF commented on app/src/main/kotlin/DBOperator.kt
> +    fun getAllCalculations() = transaction {
Правильно ли я понимаю, что при такой реализации - первый по времени запрос будет первым в списке?
Тогда лучше возвращать записи в обратном порядке.

2023-09-13 07:10 UTC, IDKWNTCMF commented on app/src/main/kotlin/DBSchema.kt
> +    val result: Column<String> = varchar("result", 255)
Почему не text?

2023-09-13 07:10 UTC, IDKWNTCMF commented on sql/cataloog_schema.sql
Поменяй на `sql/catalog_schema.sql`

2023-09-13 07:10 UTC, IDKWNTCMF commented on data/test.mv.db
Этот файл не должен лежать в репозитории.

2023-09-13 07:10 UTC, IDKWNTCMF commented on data/test.trace.db
Этот файл не должен лежать в репозитории.

2023-09-13 07:15 UTC, FedMam commented on app/src/main/kotlin/DBOperator.kt
> +    fun getAllCalculations() = transaction {
А мне здесь что-то менять или убрать reversed?

2023-09-13 07:16 UTC, FedMam commented on app/src/main/kotlin/DBSchema.kt
> +    val result: Column<String> = varchar("result", 255)
У нас результат - максимум дробное число (мы же не будем хранить его до 10000-го знака) или сообщение об ошибке

2023-09-13 07:17 UTC, FedMam commented on sql/cataloog_schema.sql
Я хотел, чтобы база данных называлась прикольно - cataloog, по аналогии с calcoolator

2023-09-13 07:17 UTC, FedMam commented on data/test.mv.db
Так это же и есть сама база данных

2023-09-13 07:18 UTC, FedMam commented on data/test.trace.db
Ну этот, наверное, не должен. Как я понял, это лог базы

2023-09-13 07:22 UTC, FedMam commented on data/test.mv.db
А, стоп, это же тестовая. Но всё равно без неё код не будет работать (пока я не добавил тесты)

2023-09-13 07:55 UTC, IDKWNTCMF commented on app/src/main/kotlin/DBOperator.kt
> +    fun getAllCalculations() = transaction {
Нет, здесь всё ок. `reverse` не заметил сначала.

2023-09-13 07:58 UTC, IDKWNTCMF commented on app/src/main/kotlin/DBSchema.kt
> +    val result: Column<String> = varchar("result", 255)
Не будем, округляться будет внутри калькулятора

2023-09-13 07:59 UTC, IDKWNTCMF commented on data/test.mv.db
А пустым его сделать нельзя и добавить в `.gitignore`?

2023-09-13 08:00 UTC, IDKWNTCMF commented on data/test.trace.db
Тогда удаляй и добавь в `.gitignore`

2023-09-13 08:00 UTC, IDKWNTCMF commented on sql/cataloog_schema.sql
Может тогда просто `sql/calcoolations.sql`?

2023-09-13 08:07 UTC, FedMam commented on app/src/main/kotlin/DBSchema.kt
> +    val result: Column<String> = varchar("result", 255)
Так что можно использовать varchar. В SQLServer text весит на 2 байта больше

2023-09-13 08:08 UTC, FedMam commented on sql/cataloog_schema.sql
Ну можно, хотя entity-класс называется Calculations

2023-09-13 08:08 UTC, FedMam commented on data/test.mv.db
Я её уберу. Тесты будут создавать базу и потом удалять

2023-09-13 15:42 UTC, FedMam commented on app/src/main/kotlin/DBOperator.kt
> +    fun getCalculations(num: Int) = transaction {
Сделал

2023-09-13 15:44 UTC, FedMam commented on app/src/main/kotlin/DBSchema.kt
> +    val result: Column<String> = varchar("result", 255)
Комментарий: теперь буду вместо "Сделал" отправлять 🚀

2023-09-13 20:58 UTC, sergeyrid commented on app/sql/cataloog_schema.sql
Кажется, что это ссылка, а не настоящий файл, и из-за этого падают тесты

2023-09-14 06:03 UTC, IDKWNTCMF commented on app/sql/cataloog_schema.sql
Эта ссылка работает, но только на Unix-подобных системах

2023-09-14 06:47 UTC, IDKWNTCMF requested changes

2023-09-14 06:47 UTC, IDKWNTCMF commented on app/src/main/kotlin/DBOperator.kt
> +            Calculation.new {
Дублирование кода, которого можно избежать

2023-09-14 06:47 UTC, IDKWNTCMF commented on app/src/main/kotlin/DBOperator.kt
> +            Calculation.new {
Лучше сделать `forEach`

2023-09-14 06:47 UTC, IDKWNTCMF commented on app/src/main/kotlin/DBOperator.kt
> +            dbFileName
Вынеси в отдельную функцию

2023-09-14 06:47 UTC, IDKWNTCMF commented on app/src/main/kotlin/DBOperator.kt
> +            dbFileName.trim().removeSuffix(".db").removeSuffix(".mv")
Дублирование кода, которого можно избежать

2023-09-14 06:47 UTC, IDKWNTCMF commented on app/src/main/kotlin/DBOperator.kt
> +            dbFileName.trim().removeSuffix(".db").removeSuffix(".mv")
Дублирование кода, которого можно избежать

2023-09-14 06:47 UTC, IDKWNTCMF commented on app/src/test/kotlin/DBTest.kt
> +        val calcRaw2 = CalculationRaw("abcd", "efgh", true)
Лучше чтобы тесты отражали реальное поведение

2023-09-14 06:47 UTC, IDKWNTCMF commented on .gitignore
> +/data/*.trace.db
Почему не `/data/`?

2023-09-14 06:47 UTC, IDKWNTCMF commented on data/test.mv.db
Это минимальный размер?

2023-09-14 06:47 UTC, IDKWNTCMF commented on data/test.trace.db
Delete this

2023-09-14 06:47 UTC, IDKWNTCMF commented on app/src/main/kotlin/DBOperator.kt
> +                    schemaQueryFileName.trim().removeSuffix(".sql")
Тоже в отдельную функцию

2023-09-14 06:47 UTC, IDKWNTCMF commented on app/src/main/kotlin/DBOperator.kt
> +                queryFileName.trim().removeSuffix(".sql")
Дублирование кода, которого можно избежать

2023-09-14 06:48 UTC, IDKWNTCMF commented on app/src/test/kotlin/DBTest.kt
> +                        // Поскольку они возвратились в обратном порядке,
За поясняющие комментарии - респект

2023-09-14 06:49 UTC, IDKWNTCMF commented on app/src/test/kotlin/DBTest.kt
Подробные тесты - это хорошо

2023-09-14 15:10 UTC, FedMam commented on .gitignore
> +/data/*.trace.db
Нельзя, там будет настоящая БД

2023-09-14 15:11 UTC, FedMam commented on app/src/test/kotlin/DBTest.kt
> +        val calcRaw2 = CalculationRaw("abcd", "efgh", true)
А для теста longTest нельзя оставить так?

2023-09-14 15:13 UTC, FedMam commented on app/sql/cataloog_schema.sql
Поправил ссылку, теперь тесты проходят

2023-09-14 15:34 UTC, IDKWNTCMF commented on app/src/test/kotlin/DBTest.kt
> +        val calcRaw2 = CalculationRaw("abcd", "efgh", true)
Да, оставь

2023-09-14 15:35 UTC, IDKWNTCMF commented on .gitignore
> +/data/*.trace.db
Но мы же не хотим её изменения в git заливать

2023-09-14 17:02 UTC, FedMam commented on .gitignore
> +/data/*.trace.db
Изменения не хотим, но саму пустую базу - хотим. Впрочем, вы можете сделать, чтобы приложение создавало базу, если не обнаружило её. Я сейчас сделаю для этого пару вещей.

2023-09-14 18:47 UTC, IDKWNTCMF approved these changes

2023-09-14 18:48 UTC, merged