Create Calculator.kt
sergeyrid/calcoolator pull request #2
Opened 2023-09-14 21:11 UTC by ksenia274

2023-09-14 22:05 UTC, sergeyrid requested changes

2023-09-14 22:05 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +
Здесь возможно ещё нужно флаг `prevIsDigit` выключать, сейчас выражение "1 - 1" падает вроде бы из-за этого

2023-09-14 22:05 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +            c == ' ' -> continue
Не уверен, что мы всегда хотим все пробелы пропускать, сейчас "1 2 3" парсится как число 123 например

2023-09-14 22:05 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +fun precedence(operator: Char): Int {
Этот метод должен быть приватным

2023-09-14 22:05 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +        else -> 0
Тут возможно стоит кидать ошибку

2023-09-14 22:05 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +                    if (b != 0.0) stack.push(a / b)
Не стоит проверять double на точное равенство нулю. При делении на 0 получается `Infinity`, и оно может получиться и по-другому, например "9 ^ 999". Я думаю, лучше его отлавливать и возвращать ошибку

2023-09-14 22:05 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +            c == '.' -> {
Сейчас мы не поддерживаем запись чисел ".1" и "1.". Я думаю, что в идеале обе должны работать

2023-09-14 22:05 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +    val result = calculator.calculateRPN(postfix)
Наверное удобнее сделать публичный метод класса, который принимает expression и возвращает сразу результат, а методы `toPostfix` и `calculateRPN` сделать приватными

2023-09-14 22:05 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +fun main(){
Когда будут тесты, main нужно будет удалить

2023-09-14 22:05 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +fun writeToFile(filePath: String, content: String) {
Зачем нам запись в файл?

2023-09-14 22:05 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +fun readFromFile(filePath: String): String {
Зачем нам чтение из файла?

2023-09-14 22:05 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +fun toPostfix(expression: String): String {
Внутри класса нет отступа, и есть ещё мелкие проблемы со стилем, которые идея может автоматически исправить через `пкм по файлу` -> `Reformat code`

2023-09-14 22:05 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +
Стоит удалить лишние пустые строки

2023-09-14 22:17 UTC, ksenia274 commented on app/src/main/kotlin/Calculator.kt
> +            c == ' ' -> continue
тут не совсем понимаю, когда нам не нужно 1 2 3 парсить как 123.  Или предлагаешь тогда Wrong Argument бросать?

2023-09-14 22:21 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +            c == ' ' -> continue
Думаю да, лучше кидать ошибку, иначе будут совсем нечитаемые выражения считаться правильными. Видимо в качестве правила можно сказать, что если происходит пробел, то число заканчивается. И при этом 2 числа подряд должны вызывать ошибку

2023-09-14 22:22 UTC, ksenia274 commented on app/src/main/kotlin/Calculator.kt
> +fun main(){
естессна

2023-09-14 22:25 UTC, ksenia274 commented on app/src/main/kotlin/Calculator.kt
> +fun readFromFile(filePath: String): String {
нам будут все готовеньким давать?

2023-09-14 22:30 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +fun readFromFile(filePath: String): String {
Насколько я понимаю, да, нам должны посылать строки из gui

2023-09-15 08:34 UTC, sergeyrid requested changes

2023-09-15 08:34 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +                        while (operators.last() != '(') {
Тут нужно падать с ошибкой, если `parenthesesCount` равен 0

2023-09-15 08:34 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +                        if (!(a / b).isInfinite()) stack.push(a / b)
Всё ещё можно получить `Infinity` другими способами, наверное можно делать проверку в самом конце вычислений

2023-09-15 08:34 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +        return stack.pop()
На пустое выражение возвращается не `IllegalArgumentException`, а `EmptyStackException`, нужно обработать этот случай. В других случаях тоже `EmptyStackException` может вылетать, например для выражения "+ 1". Нужно либо в методе `toPostfix` все эти случаи отдельно обрабатывать, либо в этом методе ловить `EmptyStackException` и перебрасывать `IllegalArgumentException`. Ещё на все эти варианты стоит добавить тесты

2023-09-15 08:34 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +                    c == '.' -> {
Выражения ".1" и "1." всё ещё не работают, мы в итоге просто не будем их поддерживать?

2023-09-15 08:34 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +    fun toPostfix(expression: String): String {
Может быть всё-таки сделать методы `toPostfix` и `calculateRPN` приватными, и в отдельном публичном методе вызывать их по-очереди? Я не понимаю, зачем может понадобиться отдельно `toPostfix` вызывать

2023-09-15 08:34 UTC, sergeyrid commented on app/src/test/kotlin/CalcTest.kt
> +class CalcTest {
С тестами в целом всё хорошо, но можно больше тестов на разные крайние случаи добавить

2023-09-15 08:38 UTC, sergeyrid commented
Ещё баг нашёл: "0 - 1 - 1" возвращает в результате 0

2023-09-15 10:32 UTC, ksenia274 commented on app/src/main/kotlin/Calculator.kt
> +                    c == '.' -> {
Не, я и не хотела их поддерживать

2023-09-15 15:11 UTC, sergeyrid requested changes

2023-09-15 15:11 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +        } catch (e: Exception) {
Так не очень хорошо делать, лучше конкретные исключения ловить. В данном случае видимо только `java.util.EmptyStackException`

2023-09-15 15:11 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +        return result
Можно убрать переменную `result`, типа `return calculateRPN(toPostfix(expression))`

2023-09-15 15:11 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +            postfix += " " + "${operators.removeLast()}"
Можно поменять на `" ${operators.removeLast()}"`

2023-09-15 15:11 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +                            postfix += " " + "${operators.removeLast()}"
Можно поменять на `" ${operators.removeLast()}"`

2023-09-15 15:11 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +                            postfix += " " + "${operators.removeLast()}"
Можно поменять на `" ${operators.removeLast()}"`

2023-09-15 15:11 UTC, sergeyrid commented on app/src/main/kotlin/Calculator.kt
> +                    else -> {
Сюда попадают все некорректные символы и парсятся как операторы, из-за этого с неправильной ошибкой падает например "1 a 1". Лучше здесь явным образом перечислить все возможные операторы, а в else кидать ошибку

2023-09-15 20:50 UTC, sergeyrid approved these changes

2023-09-15 20:54 UTC, ksenia274 commented
Back is ready

2023-09-15 20:55 UTC, merged